version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-2
  aws-cli:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    volumes:
      - ./testbucket:/aws
      - ./tests/data:/test/data
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket images-claim-check --region us-east-1
        aws --endpoint-url=http://localstack:4566 s3 cp /test/data/dosimetria.svg s3://images-claim-check/raw/3b18f590-5b12-4b35-a1a0-48eae865f2e4/
      "